name: Run Tests

on:
  pull_request:

jobs:
  test:
    name: Run Presto Go Client Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Install Docker
      run: |
        sudo apt-get update
        sudo apt-get install -y docker.io
        sudo systemctl start docker
        sudo usermod -aG docker $USER

    - name: Verify Docker Installation
      run: docker --version

    - name: Run integration tests
      env:
        PRESTO_SERVER_DSN: "http://test@localhost:8080" # Replace with actual DSN if required
      run: |
        chmod +x integration_tests/run.sh
        ./integration_tests/run.sh

